development: &development
  adapter: postgresql
  host: localhost
  database: bjond_facebook_ad_app_dev
  encoding: unicode
  
test: &test
  adapter: postgresql
  host: localhost
  database: bjond_facebook_ad_app_test
  encoding: unicode 